version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"


  calendar:
    image: calendar:latest
    container_name: calendar
    restart: always
    depends_on:
      - rabbitmq  # Ensures RabbitMQ starts first
    ports:
      - "5001:5001"
      - "8090:8090"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASSWORD}

